# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: faf4662967ccbcfde9443adb380c47b213b91fe0e43f6b82bbb628c0967b82df7af60cb356eb344e2a9f2333b5bfef1c64ed0a616dd317f9a5e8536820122d5d

test:
  secret_key_base: 778b135675dd821b71748cc5846dd1999d317c4e9ce16fa81691d9cab79e9f0c77b410a70d64c92b1bedfdb5ca57b04ba9c05bbc7143d4d3f2a9c777e2c74cc4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
